import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = <Locale>[
    Locale('de'),
    Locale('en'),
  ];

  static AppLocalizations of(BuildContext context) {
    final localization =
        Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(localization != null, 'AppLocalizations not found in context');
    return localization!;
  }

  String tr(String key, [Map<String, Object> params = const {}]) {
    final languageCode = locale.languageCode;
    var value = _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
    if (languageCode == 'de') {
      value = _normalizeGermanUmlauts(value);
      value = _fixGermanUmlautExceptions(value);
    }
    params.forEach((paramKey, paramValue) {
      value = value.replaceAll('{$paramKey}', '$paramValue');
    });
    return value;
  }

  static String _normalizeGermanUmlauts(String input) {
    return input
        .replaceAll('Ae', '\u00C4')
        .replaceAll('Oe', '\u00D6')
        .replaceAll('Ue', '\u00DC')
        .replaceAll('ae', '\u00E4')
        .replaceAll('oe', '\u00F6')
        .replaceAll('ue', '\u00FC');
  }

  static String _fixGermanUmlautExceptions(String input) {
    return input
        .replaceAll('akt\u00FCll', 'aktuell')
        .replaceAll('n\u00FCen', 'neuen')
        .replaceAll('he\u00FCte', 'heute');
  }

  static const Map<String, Map<String, String>> _localizedValues =
      <String, Map<String, String>>{
    'de': <String, String>{
      'dashboard': 'Dashboard',
      'warehouses': 'Lager',
      'viewer': '3D Ansicht',
      'profile': 'Profil',
      'tours': 'Touren',
      'controlTower': 'Leitstand',
      'settings': 'Einstellungen',
      'settingsSubtitle':
          'System, Sprache und Viewer-Verhalten zentral konfigurieren.',
      'notifications': 'Benachrichtigungen',
      'controlTowerTitle': 'Live-Leitstand',
      'controlTowerSubtitle':
          'Operativer Ueberblick ueber Auslastung, Risiken und Lagerstatus.',
      'controlTowerHint':
          'Live-Ueberblick ueber Auslastung, Risiken und Meldungen.',
      'openControlTower': 'Leitstand oeffnen',
      'controlTowerSystemStatus': 'Systemstatus',
      'controlTowerStatusStable': 'Betrieb stabil',
      'controlTowerStatusAttention': 'Aufmerksamkeit erforderlich',
      'controlTowerUpdatedAt': 'Aktualisiert {time}',
      'controlTowerLiveAt': 'Live {time}',
      'controlTowerOnlineLabel': 'Online',
      'controlTowerLimitedLabel': 'Eingeschraenkt',
      'controlTowerMaintenanceLabel': 'Wartung',
      'controlTowerPriorityTitle': 'Priorisierte Lager',
      'controlTowerPrioritySubtitle':
          'Lager mit hohem Risiko oder hoher Auslastung zuerst pruefen.',
      'controlTowerActionsTitle': 'Schnellaktionen',
      'controlTowerActionsSubtitle':
          'Direkter Zugriff auf Lagerliste, 3D-Ansicht und Meldungen.',
      'controlTowerOpenWarehouses': 'Lager oeffnen',
      'controlTowerOpenViewer': '3D-Ansicht oeffnen',
      'controlTowerOpenTours': 'Touren oeffnen',
      'controlTowerOpenNotifications': 'Meldungen oeffnen',
      'controlTowerOpenTickets': 'Tickets ({count})',
      'controlTowerOverdueTickets': 'SLA ueberfaellige Tickets',
      'controlTowerAutoEscalations': 'Auto-Eskalationen (60 Min)',
      'controlTowerAutoEscalationAlert':
          '{count} neue Auto-Eskalation(en) in den letzten 5 Minuten',
      'controlTowerOpenCriticalTickets': 'Kritische Tickets',
      'criticalTicketsPanelSubtitle':
          'Direkter Zugriff auf die aktuell wichtigsten offenen Tickets.',
      'controlTowerAcknowledgeAlert': 'Hinweis quittieren',
      'controlTowerAlertAcknowledged': 'Auto-Eskalationshinweis quittiert.',
      'controlTowerAcknowledgeAll': 'Alle quittieren',
      'controlTowerEventsOpenCount': '{count} offene Ereignisse',
      'controlTowerEventsOpenEscalatedCount':
          '{open} offen | {escalated} eskaliert',
      'controlTowerNoFilteredEvents': 'Keine Ereignisse fuer den aktuellen Filter.',
      'controlTowerAcknowledgeNoPermission':
          'Keine Berechtigung fuer diese Aktion oder nichts zu quittieren.',
      'controlTowerEventAcknowledgedMsg': '{title} wurde quittiert.',
      'controlTowerAllAcknowledgedMsg': '{count} Ereignisse wurden quittiert.',
      'controlTowerEventEscalatedMsg': '{title} wurde eskaliert.',
      'controlTowerEscalateNoPermission':
          'Keine Berechtigung fuer Eskalationen oder bereits eskaliert.',
      'controlTowerAuditTitle': 'Aktivitaetsprotokoll',
      'controlTowerAuditSubtitle':
          'Nachvollziehbare Aktionen im Leitstand (Quittierung/Eskalation).',
      'controlTowerAuditEmpty': 'Noch keine Aktionen protokolliert.',
      'controlTowerAuditLine': '{action} von {user} ({time})',
      'controlTowerAuditBulkAcknowledgeTitle':
          '{count} Ereignisse gesammelt quittiert',
      'auditActionAcknowledged': 'Quittiert',
      'auditActionEscalated': 'Eskaliert',
      'auditActionAcknowledgedAll': 'Alle quittiert',
      'controlTowerActionPermissionHint':
          'Einige Aktionen sind fuer deine Rolle eingeschraenkt.',
      'eventFilterOpen': 'Offen',
      'eventFilterAcknowledged': 'Quittiert',
      'eventFilterEscalated': 'Eskaliert',
      'eventFilterAll': 'Alle',
      'eventAcknowledged': 'Quittiert',
      'eventAcknowledge': 'Quittieren',
      'eventEscalated': 'Eskaliert',
      'eventEscalate': 'Eskalieren',
      'eventSlaDueIn': 'SLA in {minutes} Min',
      'eventSlaBreached': 'SLA +{minutes} Min',
      'controlTowerTicketsTitle': 'Control-Tower Tickets',
      'controlTowerTicketsCount':
          '{open} offen von {all} Tickets | {overdue} SLA ueberfaellig',
      'controlTowerTicketsSearchHint': 'Nach Ticketinhalt oder Bearbeiter suchen',
      'controlTowerTicketsEmptyTitle': 'Keine Tickets',
      'controlTowerTicketsEmptyMessage':
          'Aktuell liegen keine eskalationspflichtigen Tickets vor.',
      'criticalTicketsAction': 'Kritische Tickets',
      'ticketCriticalOnly': 'Nur kritische Tickets',
      'ticketSortLabel': 'Sortierung',
      'ticketSortSla': 'SLA zuerst',
      'ticketSortEscalation': 'Eskalation zuerst',
      'ticketSortNewest': 'Neueste zuerst',
      'ticketSortSlaShort': 'SLA',
      'ticketSortEscalationShort': 'Esk',
      'ticketSortNewestShort': 'Neu',
      'ticketCriticalBadge': 'Kritisch',
      'controlTowerTicketUpdateFailed':
          'Ticket konnte nicht aktualisiert werden.',
      'ticketOverdueOnly': 'Nur SLA ueberfaellig',
      'ticketOpenDetails': 'Details',
      'ticketEscalationAll': 'Alle Eskalationsstufen',
      'ticketDetailsTitle': 'Ticketdetails',
      'ticketDetailsNotFoundTitle': 'Ticket nicht gefunden',
      'ticketDetailsNotFoundMessage':
          'Das Ticket konnte nicht geladen werden oder wurde entfernt.',
      'ticketTimelineTitle': 'Ticketverlauf',
      'ticketNoTimeline': 'Noch keine Aktivitaeten vorhanden.',
      'ticketCommentHint': 'Kommentar verfassen...',
      'ticketAddComment': 'Kommentar senden',
      'ticketCommentAdded': 'Kommentar wurde gespeichert.',
      'ticketCommentFailed': 'Kommentar konnte nicht gespeichert werden.',
      'ticketUpdatedBy': 'von {user} ({time})',
      'ticketActivityCreated': 'Ticket erstellt',
      'ticketActivityStatusChanged': 'Status geaendert: {old} -> {new}',
      'ticketActivityEscalationChanged':
          'Eskalationsstufe geaendert: {old} -> {new}',
      'ticketActivityEscalationAuto':
          'SLA-Verstoss: Automatische Eskalation {old} -> {new}',
      'ticketActivityAssigned': 'Zugewiesen an {assignee}',
      'ticketActivityCommented': 'Kommentar: {comment}',
      'ticketLevelL1': 'L1',
      'ticketLevelL2': 'L2',
      'ticketLevelL3': 'L3',
      'ticketSlaDueIn': 'Ticket-SLA in {minutes} Min',
      'ticketSlaBreached': 'Ticket-SLA +{minutes} Min',
      'ticketSlaBreachedShort': 'SLA seit {minutes} Min ueberfaellig',
      'ticketSlaResolved': 'SLA erledigt',
      'ticketAssignee': 'Bearbeiter',
      'ticketUnassigned': 'Nicht zugewiesen',
      'ticketCreatedBy': 'Erstellt von',
      'ticketAssignAction': 'Zuweisen',
      'ticketQuickAssignMeDone': 'Ticket wurde dir zugewiesen.',
      'ticketQuickEscalateL3Done': 'Ticket wurde auf L3 eskaliert.',
      'ticketStatusOpen': 'Offen',
      'ticketStatusInProgress': 'In Bearbeitung',
      'ticketStatusResolved': 'Geloest',
      'severity': 'Prioritaet',
      'controlTowerEventsTitle': 'Live Ereignisse',
      'controlTowerEventsSubtitle':
          'Meldungen aus Lager, Touren und Bestand in Echtzeit.',
      'controlTowerNoEvents': 'Keine kritischen Ereignisse vorhanden.',
      'eventTypeWarehouse': 'Lager',
      'eventTypeTour': 'Tour',
      'eventTypeRamp': 'Rampe',
      'eventTypeInventory': 'Bestand',
      'eventWarehouseTitle': 'Lagerstatus',
      'eventWarehouseMaintenance': '{name} befindet sich im Wartungsmodus.',
      'eventWarehouseUtilization':
          '{name} meldet hohe Auslastung ({utilization}%).',
      'eventWarehouseOnline': '{name} laeuft stabil im Regelbetrieb.',
      'eventTourTitle': 'Tourstatus',
      'eventTourDelayed':
          'Tour {code} ({vehicle}) ist verspaetet.',
      'eventRampTitle': 'Rampenauslastung',
      'eventRampLoadLow': 'Tour {code} hat nur {load}% Beladung.',
      'eventNotificationTitle': 'Systemmeldung',
      'eventNotificationMessage': '{message}',
      'welcome': 'Willkommen, {name}',
      'searchToWarehouse': 'Zur Lager-Suche und Filterung',
      'filtersReset': 'Filter zuruecksetzen',
      'latestWarehouse': 'Zuletzt geoeffnetes Lager',
      'badgeNoSelection': 'Kein Lager',
      'badgeFiltered': 'Gefiltert',
      'badgeAll': 'Alle',
      'badgeInactive': 'Inaktiv',
      'badgeReady': 'Bereit',
      'badgeEmpty': 'Keine',
      'badgeSaved': 'Gespeichert',
      'badgeAttention': 'Achtung',
      'badgeStable': 'Stabil',
      'none': 'Keins',
      'pleaseSelectWarehouse': 'Bitte Lager auswaehlen',
      'hitsWarehouses': 'Treffer Lager',
      'filteredFrom': 'Gefiltert aus {count} Standorten',
      'allAvailable': 'Alle verfuegbaren Standorte',
      'quick3d': 'Schnellzugriff 3D',
      'tourDashboardSubtitle': '{delayed} verspaetet',
      'notActive': 'Nicht aktiv',
      'ready': 'Bereit',
      'viewerWarehouse': 'Lager: {name}',
      'favorites': 'Favoriten',
      'favoritesEmpty': 'Noch keine Favoriten gesetzt',
      'favoritesInfo': 'Markierte Lager fuer Schnellzugriff',
      'statusDistribution': 'Statusverteilung',
      'statusFilter': 'Statusfilter',
      'onlineCount': '{count} Online',
      'limitedCount': '{count} Eingeschraenkt',
      'maintenanceCount': '{count} Wartung',
      'selectedCount': '{count} Lager in der aktuellen Auswahl',
      'searchHint': 'Lagername oder Standort suchen',
      'all': 'Alle',
      'warehousesCount': '{shown} von {all} Standorten',
      'noWarehousesFound': 'Keine Lager gefunden',
      'adjustFilters': 'Passe Suche oder Statusfilter an.',
      'noWarehouseData': 'Aktuell sind keine Lagerdaten verfuegbar.',
      'open3d': '3D Ansicht',
      'removeFavorite': 'Aus Favoriten entfernen',
      'markFavorite': 'Als Favorit markieren',
      'selectedWarehouseMsg': '{name} wurde ausgewaehlt.',
      'favoriteAddedMsg': '{name} als Favorit gespeichert.',
      'favoriteRemovedMsg': '{name} aus Favoriten entfernt.',
      'close': 'Schliessen',
      'open3dView': '3D Ansicht oeffnen',
      'zones': 'Zonen',
      'id': 'ID',
      'location': 'Standort',
      'status': 'Status',
      'name': 'Name',
      'splashSubtitle': 'Digitale Lager-Visualisierung',
      'loadingA': 'Initialisiere Lagerdaten...',
      'loadingB': 'Verbinde Viewer-Komponenten...',
      'loadingC': 'Bereite Dashboard vor...',
      'login': 'Anmelden',
      'email': 'E-Mail',
      'password': 'Passwort',
      'forgotPassword': 'Passwort vergessen',
      'demoLogin': 'Demo-Login',
      'enterEmail': 'E-Mail eingeben',
      'enterPassword': 'Passwort eingeben',
      'loginSuccess': 'Erfolgreich angemeldet.',
      'loginMissing': 'Bitte E-Mail und Passwort eingeben.',
      'passwordResetInactive': 'Passwort-Reset ist für den MVP noch nicht aktiv.',
      'emptyViewerTitle': 'Kein Lager ausgewählt',
      'emptyViewerMessage':
          'Wähle zuerst ein Lager aus der Lagerliste, um die 3D-Ansicht zu starten.',
      'toWarehouseList': 'Zur Lagerliste',
      'toDashboard': 'Zum Dashboard',
      'adapter': 'Adapter: {name}',
      'viewerCanvasTitle': '3D Lageransicht',
      'viewerFullscreenTour': 'Vollbild Rundgang',
      'viewerControlsHint':
          'Wischen = drehen, Zwei Finger = zoomen, Tippen = Fokus',
      'viewerQuickActionsTitle': 'Schnellaktionen',
      'viewerQuickActionsHint': 'Steuerung direkt am Modell',
      'viewerReset': 'Ansicht zuruecksetzen',
      'viewerShowZones': 'Zonen anzeigen',
      'viewerHideZones': 'Zonen ausblenden',
      'viewerStartTour': 'Rundgang starten',
      'viewerPauseTour': 'Rundgang pausieren',
      'viewerTourHeader': '{name} - {status} - Orbit/FP wählen',
      'viewerLegendShow': 'Legende anzeigen',
      'viewerLegendHide': 'Legende ausblenden',
      'viewerLegendTitle': 'Legende',
      'viewerLegendHeatmapOn': 'Heatmap aktiv auf Regalen',
      'viewerLegendHeatmapOff': 'Heatmap derzeit ausgeblendet',
      'viewerShowHeatmap': 'Heatmap anzeigen',
      'viewerHideHeatmap': 'Heatmap ausblenden',
      'storageLocationTitle': 'Lagerplatz-Auswahl',
      'storageLocationSubtitle':
          'Regal, Ebene und Fach gezielt ansteuern.',
      'storageLocationRackLabel': 'Regal',
      'storageLocationLevelLabel': 'Ebene',
      'storageLocationSlotLabel': 'Fach',
      'storageLocationSlotHelper': '1 bis {max}',
      'storageLocationSlotInvalid':
          'Bitte eine gueltige Fachnummer eingeben.',
      'storageLocationSummary':
          'Auswahl: Regal {rack} · Ebene {level} · Fach {slot}',
      'storageLocationFocusAction': 'Lagerplatz anzeigen',
      'storageLocationFocusToast':
          'Fokus gesetzt: Regal {rack}, Ebene {level}, Fach {slot}',
      'storageLocationCodeLabel': 'Positionscode',
      'storageLocationCodeHint': 'z. B. R01-E03-F010',
      'storageLocationCodeApply': 'Code anwenden',
      'storageLocationCodeInvalid':
          'Bitte ein gueltiges Format wie R01-E03-F010 eingeben.',
      'storageLocationSamplesTitle': 'Echte Lagerplätze (Beispiel)',
      'storageLocationSamplesSubtitle':
          'Kleine Stichprobe direkt aus warehouse.db.',
      'storageLocationSamplesEmpty':
          'Noch keine echten Lagerplätze aus warehouse.db geladen.',
      'storageLocationSamplesCount': '{count} von {total}',
      'storageLocationVisibleCount': '{count} von {total} sichtbar',
      'storageLocationShowMore': 'Mehr anzeigen',
      'storageLocationShowLess': 'Weniger anzeigen',
      'storageLocationFilterLabel': 'Lagerplatz suchen',
      'storageLocationFilterHint': 'Regal, Ebene, Fach oder Code',
      'storageLocationFilterClear': 'Filter löschen',
      'storageLocationSuggestionsTitle': 'Vorschläge',
      'storageLocationSortAbc': 'Sortierung: ABC',
      'storageLocationSortRack': 'Sortierung: Regal',
      'storageLocationViewInViewer': 'Im Viewer anzeigen',
      'storageLocationDetailsTitle': 'Lagerplatz-Details',
      'storageLocationDetailsSubtitle':
          'Ausgewählter Lagerplatz mit Detailfeldern.',
      'storageLocationDetailsEmpty':
          'Wähle einen Lagerplatz, um Details zu sehen.',
      'storageLocationFieldPlace': 'Platz-ID',
      'storageLocationFieldArea': 'Bereich',
      'storageLocationFieldAbc': 'ABC-Klasse',
      'storageLocationFieldStatus': 'Status',
      'storageLocationFieldRack': 'Regal',
      'storageLocationFieldLevel': 'Ebene',
      'storageLocationFieldSlot': 'Fach',
      'warehouseAreaLabel': 'Bereich',
      'warehouseStatusShort': 'Status',
      'heatmapMetricLabel': 'Heatmap Metrik',
      'heatmapMetricChangedMsg': 'Heatmap-Metrik: {metric}',
      'heatmapLegendTitle': 'Heatmap: {metric}',
      'heatmapActiveState': 'Heatmap aktiv ({metric})',
      'heatmapInactiveState': 'Heatmap aus',
      'heatmapMetricUtilization': 'Auslastung',
      'heatmapMetricPickRate': 'Pickrate',
      'heatmapMetricCongestion': 'Staudichte',
      'heatmapMetricAbcA': 'A-Anteil',
      'heatmapOverviewTitle': 'Heatmap Uebersicht',
      'heatmapOverviewSubtitle': 'Schneller Blick auf Top-Zone und Schweregrade.',
      'heatmapTopZoneLabel': 'Top-Zone',
      'heatmapAverageLabel': 'Durchschnitt: {value}',
      'heatmapSeverityHigh': 'Hoch',
      'heatmapSeverityMedium': 'Mittel',
      'heatmapSeverityLow': 'Niedrig',
      'heatmapFocusTopZone': 'Top-Zone fokussieren',
      'heatmapOpenTopZoneDetails': 'Top-Zone Details',
      'heatmapZoneTypeLabel': 'Zonentyp',
      'heatmapZoneTypeInbound': 'Wareneingang',
      'heatmapZoneTypePicking': 'Kommissionierung',
      'heatmapZoneTypeShipping': 'Versand',
      'heatmapZoneTypeStorage': 'Lager',
      'heatmapZoneTypeOther': 'Sonstige',
      'heatmapNoZonesForType': 'Keine Zonen fuer den ausgewaehlten Typ vorhanden.',
      'heatmapCriticalZonesTitle': 'Top Problemzonen',
      'heatmapLiveBadge': 'Live',
      'heatmapAutoFocusActive': 'Auto-Fokus aktiv',
      'heatmapLivePause': 'Live-Modus pausieren',
      'heatmapLiveStart': 'Live-Modus starten',
      'heatmapAutoFocusPause': 'Auto-Fokus pausieren',
      'heatmapAutoFocusStart': 'Auto-Fokus starten',
      'heatmapNoZonesForSelectedFilters':
          'Keine Zonen im ausgewaehlten Prioritaetsbereich.',
      'zonesVisible': 'Zonen sichtbar',
      'zonesHidden': 'Zonen ausgeblendet',
      'tourActive': 'Rundgang aktiv',
      'tourPaused': 'Rundgang pausiert',
      'resets': 'Resets: {count}',
      'zonesHiddenMsg': 'Zonenansicht ausgeblendet.',
      'tourPausedMsg': 'Rundgang pausiert.',
      'viewerNoModelZonesForFocus': 'Keine Modellzonen fuer Fokus vorhanden.',
      'viewerFocusCriticalZoneMsg': 'Fokus auf kritische Zone: {zone}',
      'viewerFocusCriticalZoneAction': 'Kritische Zone fokussieren',
      'role': 'Rolle: {role}',
      'logout': 'Logout',
      'language': 'Sprache',
      'languageGerman': 'Deutsch',
      'languageEnglish': 'English',
      'notificationsToggle': 'Benachrichtigungen',
      'notificationsDemoSetting': 'Lokale Demo-Einstellung',
      'settingsAutoSaveStatus': 'Automatische Speicherung',
      'settingsLastSavedAt': 'Zuletzt gespeichert: {time}',
      'settingsNeverSaved': 'Noch keine Aenderung gespeichert',
      'settingsTransferTitle': 'Einstellungen uebertragen',
      'settingsTransferSubtitle':
          'Exportiert oder importiert lokale Einstellungen als JSON.',
      'settingsExportAction': 'Exportieren',
      'settingsImportAction': 'Importieren',
      'settingsExportCopied': 'Einstellungen als JSON in die Zwischenablage kopiert.',
      'settingsImportTitle': 'Einstellungen importieren',
      'settingsImportHint': 'JSON einfuegen...',
      'settingsImportPasteFromClipboard': 'Zwischenablage einfuegen',
      'settingsImportApply': 'Import anwenden',
      'settingsImportSuccess': 'Einstellungen wurden importiert.',
      'settingsImportFailed': 'Import fehlgeschlagen. JSON bitte pruefen.',
      'settingsImportValidationHint':
          'Nur ein JSON-Objekt einfuegen, z. B. {"languageCode":"de"}.',
      'settingsImportJsonValid': 'JSON-Format gueltig.',
      'settingsImportJsonInvalid':
          'JSON ungueltig. Bitte ein gueltiges JSON-Objekt einfuegen.',
      'settingsImportClipboardEmpty':
          'Zwischenablage ist leer oder enthaelt keinen Text.',
      'settingsImportClipboardLoaded':
          'Zwischenablage in den Importbereich eingefuegt.',
      'darkMode': 'Darkmode',
      'themeSwitch': 'Material 3 Themewechsel',
      'viewerIntegration': 'Viewer Integration',
      'autoEscalationSettingsTitle': 'Auto-Eskalationsregeln',
      'autoEscalationSettingsSubtitle':
          'Definiert, wann SLA-verletzte Tickets automatisch hochgestuft werden.',
      'autoEscalationPresetLabel': 'Voreinstellung',
      'autoEscalationPresetCurrent': 'Aktiv: {preset}',
      'autoEscalationPresetConservative': 'Konservativ',
      'autoEscalationPresetStandard': 'Standard',
      'autoEscalationPresetAggressive': 'Aggressiv',
      'autoEscalationPresetCustom': 'Benutzerdefiniert',
      'autoEscalationResetRules': 'Regeln auf Standard zuruecksetzen',
      'autoEscalationResetDone':
          'Auto-Eskalationsregeln wurden auf Standard gesetzt.',
      'autoEscalationFirstStepValue': 'L1 -> L2 ab {minutes} Min SLA-Verstoss',
      'autoEscalationSecondStepValue': 'L2 -> L3 ab {minutes} Min SLA-Verstoss',
      'appVersion': 'App-Version',
      'markAllRead': 'Alle gelesen',
      'noNotifications': 'Keine Benachrichtigungen',
      'noNotificationsMsg': 'Aktuell liegen keine Meldungen vor.',
      'remove': 'Entfernen',
      'justNow': 'gerade eben',
      'minutesAgo': 'vor {count} Min',
      'hoursAgo': 'vor {count} Std',
      'daysAgo': 'vor {count} Tag(en)',
      'statusOnline': 'Online',
      'statusLimited': 'Eingeschraenkt',
      'statusMaintenance': 'Wartung',
      'roleAdmin': 'Admin',
      'roleOperator': 'Operator',
      'roleViewer': 'Viewer',
      'viewerTypeNative': 'Native Platzhalter',
      'viewerTypeUnity': 'Unity',
      'viewerTypeWebView': 'WebView',
      'viewerTypeNativeDesc': 'Direkte Flutter-UI als Demo-Flaeche',
      'viewerTypeUnityDesc': 'Vorbereitung fuer Unity-basierten 3D-Viewer',
      'viewerTypeWebViewDesc': 'Vorbereitung fuer webbasierten 3D-Viewer',
      'severityInfo': 'Info',
      'severityWarning': 'Warnung',
      'severityCritical': 'Kritisch',
      'healthStable': 'Stabil',
      'healthWatch': 'Beobachten',
      'healthCritical': 'Kritisch',
      'priorityScoreBreakdownTitle': 'Score-Aufschluesselung',
      'priorityScoreFactorStatus': 'Statusfaktor',
      'priorityScoreFactorUtilization': 'Auslastungsfaktor',
      'priorityScoreFactorFlow': 'Prozessfaktor',
      'priorityScoreFactorOperations': 'Operativer Risiko-Faktor',
      'priorityScoreSummary':
          'S {status} | U {utilization} | F {flow} | O {operations}',
      'priorityScoreSummaryCompact':
          'S{status} U{utilization} F{flow} O{operations}',
      'dashboardAbcTitle': 'ABC Analyse (aktuelle Auswahl)',
      'dashboardAbcSubtitle':
          'A: Schnelldreher | B: Mittlere Drehung | C: Langsamdreher',
      'kpiAShare': 'A-Anteil',
      'kpiBShare': 'B-Anteil',
      'kpiCShare': 'C-Anteil',
      'topWarehousesTitle': 'Top Lager nach Auslastung',
      'topWarehousesSubtitle':
          'Schneller Blick auf Kapazitaet, Artikel und ABC-Verteilung.',
      'searchFilterSummaryBoth': 'Suche: "{query}" | Status: {status}',
      'searchFilterSummaryQuery': 'Suche: "{query}"',
      'searchFilterSummaryStatus': 'Status: {status}',
      'noFiltersActive': 'Keine Filter aktiv',
      'noExportPermission':
          'Deine Rolle hat keine Berechtigung fuer Exporte.',
      'reportExported':
          'Report exportiert: lager_report_{date}.csv ({count} Lager)',
      'performanceTitle': 'Lager Performance',
      'performanceSubtitle':
          'Gesamtauslastung ueber alle aktuell gefilterten Lager.',
      'kpiUtilization': 'Auslastung',
      'kpiOccupied': 'Belegt',
      'kpiFree': 'Frei',
      'kpiTotalSlots': 'Gesamtplaetze',
      'kpiArticles': 'Artikel',
      'exportReport': 'Tagesreport exportieren',
      'exportUnavailable': 'Export nicht verfuegbar',
      'warehouseTitle': 'Lagerhaeuser',
      'createWarehouse': 'Neues Lager',
      'warehouseCreateFailed': 'Lager konnte ueber API nicht erstellt werden.',
      'warehousesSyncAction': 'Mit Backend synchronisieren',
      'warehousesSyncError': 'Backend-Synchronisierung fehlgeschlagen: {error}',
      'retry': 'Erneut versuchen',
      'refreshNow': 'Aktualisieren',
      'backendOnline': 'Backend online',
      'backendOffline': 'Backend offline',
      'backendIssue': 'Backend Warnung',
      'lastSyncShort': 'Sync: {time}',
      'lastSyncUnknown': 'Sync: -',
      'viewerDataUpdated': 'Lagerdaten wurden aktualisiert.',
      'newWarehouseTitle': 'Lager erstellen',
      'warehouseNameLabel': 'Lagername',
      'warehouseLocationLabel': 'Standort',
      'warehouseZonesLabel': 'Zonen',
      'warehouseDescriptionLabel': 'Beschreibung',
      'warehouseStatusLabel': 'Status',
      'warehouseBaseData': 'Basisdaten',
      'warehouseLayoutData': 'Lagerabmessungen',
      'warehouseRackingData': 'Regalstruktur',
      'warehouseZonesData': 'Zonen',
      'warehouseLengthLabel': 'Laenge (m)',
      'warehouseWidthLabel': 'Breite (m)',
      'warehouseHeightLabel': 'Hoehe (m)',
      'rackRowsLabel': 'Anzahl Regalreihen',
      'rackLengthLabel': 'Regallaenge (m)',
      'rackWidthLabel': 'Regalbreite (m)',
      'rackLevelsLabel': 'Regalebenen',
      'aisleWidthLabel': 'Gangbreite (m)',
      'zonesInputLabel': 'Zonen (Komma/Zeile getrennt)',
      'zonesInputHint': 'z. B. Wareneingang, Kommissionierung, Versand',
      'zonesInputInvalid': 'Bitte mindestens eine Zone angeben.',
      'warehouseCapacityData': 'Kapazitaetsdaten',
      'warehouseFlowData': 'Prozessdaten',
      'warehouseAbcData': 'ABC-Daten',
      'totalStorageSlotsLabel': 'Gesamtplaetze',
      'occupiedStorageSlotsLabel': 'Belegte Plaetze',
      'articleCountLabel': 'Artikelanzahl',
      'inboundPerDayLabel': 'Wareneingang / Tag',
      'throughputPerDayLabel': 'Durchsatz / Tag',
      'pickRatePerHourLabel': 'Pickrate / Stunde',
      'aCountLabel': 'A-Artikel',
      'bCountLabel': 'B-Artikel',
      'cCountLabel': 'C-Artikel',
      'enterWarehouseName': 'Lagername eingeben',
      'enterWarehouseLocation': 'Standort eingeben',
      'zoneCountInvalid': 'Bitte mindestens 1 Zone angeben',
      'invalidNumber': 'Bitte gueltige Zahl eingeben',
      'occupiedMustBeWithinTotal': 'Belegte Plaetze muessen <= Gesamtplaetze sein',
      'cancel': 'Abbrechen',
      'warehouseCreatedMsg': '{name} wurde erstellt.',
      'warehouseUpdatedMsg': '{name} wurde aktualisiert.',
      'warehouseDeletedMsg': '{name} wurde geloescht.',
      'warehouseCreateNoPermission':
          'Deine Rolle darf keine neuen Lager anlegen.',
      'warehouseEditNoPermission':
          'Deine Rolle darf dieses Lager nicht bearbeiten.',
      'warehouseDeleteNoPermission':
          'Deine Rolle darf dieses Lager nicht loeschen.',
      'warehouseDeleteFailed': 'Lager konnte nicht geloescht werden.',
      'viewerRoleNoFavorites':
          'In der Viewer-Rolle koennen keine Favoriten bearbeitet werden.',
      'warehouseNotFound': 'Lager nicht gefunden',
      'warehouseNotFoundMessage':
          'Das angeforderte Lager konnte nicht geladen werden.',
      'warehouseIdLabel': 'Lager-ID',
      'articlesTotal': 'Artikel gesamt',
      'removeFavoriteShort': 'Favorit entfernen',
      'saveFavorite': 'Als Favorit speichern',
      'editWarehouse': 'Lager bearbeiten',
      'deleteWarehouse': 'Lager loeschen',
      'editWarehouseTitle': 'Lager bearbeiten',
      'deleteWarehouseTitle': 'Lager loeschen',
      'deleteWarehousePrompt': 'Soll das Lager "{name}" wirklich geloescht werden?',
      'deleteWarehouseWarning': 'Diese Aktion kann nicht rueckgaengig gemacht werden.',
      'confirmDelete': 'Loeschen',
      'saveChanges': 'Speichern',
      'changeWarehouseStatus': 'Status aendern',
      'warehouseStatusUpdatedMsg': '{name} Status: {status}',
      'warehouseKpiTitle': 'Leistungskennzahlen',
      'tabOverview': 'Uebersicht',
      'tabZones': 'Zonen',
      'tabPerformance': 'Performance',
      'tabOperations': 'Betrieb',
      'tabAbc': 'ABC',
      'tabTours': 'Touren',
      'tabHistory': 'Historie',
      'warehouseOperationsTitle': 'Operative Kennzahlen',
      'warehouseOperationsSubtitle':
          'Dock-Nutzung, SLA und Slot-Mix fuer den laufenden Betrieb.',
      'opsDockActive': 'Aktive Docks',
      'opsDockUtilization': 'Dock-Auslastung',
      'opsBlockedSlots': 'Blockierte Plaetze',
      'opsReservedSlots': 'Reservierte Plaetze',
      'opsAvgDwell': 'Durchschnitt Standzeit',
      'opsSlaCurrent': 'SLA aktuell',
      'opsSlaTarget': 'SLA Ziel',
      'opsSlotMixTitle': 'Slot-Mix',
      'opsHighBaySlots': 'Hochregal',
      'opsBlockStorageSlots': 'Blocklager',
      'opsShuttleSlots': 'Shuttle',
      'opsFloorStorageSlots': 'Bodenlager',
      'opsColdZones': 'Kuehlzonen',
      'opsAmbientZones': 'Normalzonen',
      'opsHazardousZones': 'Gefahrstoffzonen',
      'opsSafetyIncidents': 'Sicherheitsvorfaelle (Monat)',
      'opsQualityHolds': 'Qualitaetssperren',
      'warehouseToursTitle': 'Touren am Lager',
      'warehouseToursSubtitle': '{count} Touren sind aktuell zugeordnet.',
      'warehouseTourLine':
          '{driver} | {status} | Stopps: {stops} | Beladung: {load}%',
      'warehouseToursEmpty': 'Dieses Lager hat aktuell keine zugeordneten Touren.',
      'openTours': 'Touren oeffnen',
      'historyTitle': 'Historie & Ereignisse',
      'historySubtitle':
          'Zeitliche Uebersicht wichtiger Betriebsereignisse dieses Lagers.',
      'historySearchHint': 'Ereignisse durchsuchen',
      'historyFilterAll': 'Alle',
      'historyFilterAlert': 'Alarm',
      'historyFilterInventory': 'Bestand',
      'historyFilterPerformance': 'Performance',
      'historyFilterMaintenance': 'Wartung',
      'historyNoResults': 'Keine Ereignisse fuer den aktuellen Filter.',
      'historyAlertTitle': 'Statusereignis',
      'historyInventoryTitle': 'Bestandslauf',
      'historyPerformanceTitle': 'Performance Snapshot',
      'historyMaintenanceTitle': 'Wartungsprotokoll',
      'historyAlertMaintenanceMsg': 'Wartungsstatus aktiv fuer {name}.',
      'historyAlertHealthyMsg': 'Statuspruefung erfolgreich fuer {name}.',
      'historyInventoryMsg':
          'Bestandslauf abgeschlossen: {count} Artikel verarbeitet.',
      'historyPerformanceMsg':
          'Durchsatz heute: {throughput}/Tag | Pickrate: {pick}/h',
      'historyMaintenanceMsg':
          'Wartungsfenster fuer Foerdertechnik dokumentiert.',
      'warehouseKpiSubtitle':
          'Kapazitaet, Auslastung, Wareneingang und Durchsatz auf einen Blick.',
      'kpiOccupiedSlots': 'Belegte Plaetze',
      'kpiFreeSlots': 'Freie Plaetze',
      'kpiInboundPerDay': 'Wareneingang / Tag',
      'kpiThroughputPerDay': 'Durchsatz / Tag',
      'kpiPickRatePerHour': 'Pickrate / Stunde',
      'warehouseAbcTitle': 'ABC Analyse Lager',
      'warehouseAbcSubtitle':
          'Verteilung der Artikelklassen A/B/C fuer {count} Positionen.',
      'zoneAnalysisTitle': 'Zonenanalyse',
      'zoneAnalysisSubtitle':
          'ABC- und Leistungsdaten je Zone fuer operative Entscheidungen.',
      'zoneSlotsArticlesLine':
          'Plaetze {occupied}/{total} | Artikel {articles}',
      'zoneFlowLine':
          'Wareneingang {inbound}/Tag | Durchsatz {throughput}/Tag | Pickrate {pick}/h',
      'viewerRoleHint':
          'Hinweis: In der Viewer-Rolle sind Steuerfunktionen deaktiviert.',
      'adapterStatusActive': 'Aktiv',
      'adapterStatusPrepared': 'Vorbereitet',
      'nativeViewerName': 'Native Platzhalter-Viewer',
      'unityViewerName': 'Unity Adapter',
      'webViewViewerName': 'WebView Adapter',
      'nativePlaceholderTitle': '3D-Modell Platzhalter',
      'nativePlaceholderSubtitle':
          'Hier wird spaeter das Modell fuer {name} geladen.',
      'unityPlaceholderTitle': 'Unity Integration vorbereitet',
      'unityPlaceholderSubtitle':
          'Schnittstelle steht. Hier wird spaeter die Unity-Ansicht eingebettet.',
      'webViewPlaceholderTitle': 'WebView Integration vorbereitet',
      'webViewPlaceholderSubtitle':
          'Hier wird spaeter ein webbasierter 3D-Viewer geladen.',
      'adapterResetMessage': 'Ansicht fuer {name} wurde zurueckgesetzt.',
      'adapterShowZonesMessage':
          '{count} Zonen fuer {name} eingeblendet.',
      'adapterStartTourMessage': 'Rundgang durch {name} gestartet.',
      'adapterHeatmapShownMessage':
          'Heatmap "{metric}" fuer {name} aktiviert.',
      'adapterHeatmapHiddenMessage': 'Heatmap fuer {name} ausgeblendet.',
      'viewerGenerationTitle': 'Automatische Lageransicht',
      'viewerModelStateAvailable': 'Generiert',
      'viewerModelStateMissing': 'Nicht generiert',
      'viewerGenerationSubtitleReady':
          'Die vereinfachte Lageransicht ist vorhanden und wird unten dargestellt.',
      'viewerGenerationSubtitleMissing':
          'Erzeuge aus den Strukturdaten eine vereinfachte Lageransicht.',
      'viewerGenerateAction': 'Ansicht generieren',
      'viewerModelGeneratedAt': 'Zuletzt generiert: {time}',
      'viewerModelGeneratedSuccess': 'Lageransicht wurde erfolgreich generiert.',
      'viewerModelGeneratedError': 'Lageransicht konnte nicht generiert werden.',
      'viewerBackendOfflineInfo':
          'Backend derzeit nicht erreichbar. Die App nutzt lokale Daten (Offline-Modus).',
      'viewerGeneratedCanvasTitle': 'Generierte Lageransicht',
      'viewerModelShelves': 'Regalgitter',
      'viewerGeneratedCanvasSubtitle':
          'Schematische Darstellung fuer {name} basierend auf Layoutdaten.',
      'unityAdapterInactive':
          'Unity-Adapter ist vorbereitet, aber noch nicht aktiviert.',
      'unityZonesPending': 'Unity-Zonenanzeige folgt nach Integration.',
      'unityTourPending': 'Unity-Rundgang folgt nach Integration.',
      'unityHeatmapPending': 'Unity-Heatmap folgt nach Integration.',
      'webViewAdapterInactive':
          'WebView-Adapter ist vorbereitet, aber noch nicht aktiviert.',
      'webViewZonesPending': 'WebView-Zonenanzeige folgt nach Integration.',
      'webViewTourPending': 'WebView-Rundgang folgt nach Integration.',
      'webViewHeatmapPending': 'WebView-Heatmap folgt nach Integration.',
      'toursTitle': 'Transporttouren',
      'toursCount': '{shown} von {all} Touren',
      'tourKpiActive': 'Aktiv',
      'tourKpiDelayed': 'Verspaetet',
      'tourKpiCompleted': 'Abgeschlossen',
      'tourSearchHint': 'Nach Tourcode, Fahrer oder Fahrzeug suchen',
      'noToursFound': 'Keine Touren gefunden',
      'noToursData': 'Aktuell sind keine Tourdaten verfuegbar.',
      'tourProgressLine': 'Fortschritt {percent}% ({completed}/{total} Stopps)',
      'tourLoadLine': 'Beladung {load}% | ETA {eta}',
      'tourStopsAction': 'Stopps',
      'warehouseAction': 'Lager',
      'tourStopsTitle': 'Stopps fuer {code}',
      'tourStopsSubtitle': '{count} geplante Stopps',
      'tourStopEta': 'Geplante Ankunft',
      'tourStatusPlanned': 'Geplant',
      'tourStatusLoading': 'Beladung',
      'tourStatusInTransit': 'Unterwegs',
      'tourStatusDelayed': 'Verspaetet',
      'tourStatusCompleted': 'Abgeschlossen',
      'tourStopPending': 'Ausstehend',
      'tourStopArrived': 'Angekommen',
      'tourStopUnloaded': 'Entladen',
      'roleDemo': 'Benutzerrolle (Demo)',
      'roleDemoHint':
          'Viewer-Rolle: nur lesen | Operator/Admin: volle Aktionen',
      'accessDeniedTitle': 'Kein Zugriff',
      'accessDeniedMessage':
          'Deine Rolle hat keine Berechtigung fuer diese Seite ({path}).',
      // Order volume card
      'orderVolumeTitle': 'Auftragsvolumen',
      'orderVolumeSubtitle': 'Eingehende Auftraege je Tag aus warehouse.db.',
      'orderVolumeEmpty': 'Keine Auftragsdaten gefunden.',
      'orderVolumePerDay': 'Ø/Tag',
      'orderVolumeOrdersUnit': 'Auftraege',
      'orderVolumePeak': 'Peak',
      'orderVolumePositionsTotal': 'Positionen gesamt',
      // Pick activity heatmap
      'pickActivityTitle': 'Pick-Aktivitaet nach Stunde',
      'pickActivitySubtitle': 'Picks pro Wochentag und Stunde aus warehouse.db.',
      'pickActivityRange': 'Picks pro Wochentag und Stunde · {from} – {to}',
      'pickActivityEmpty': 'Keine Pick-Daten gefunden.',
      'pickActivityTooltip': '{day} {hour}:00 · {picks} Picks',
      'pickActivityTotalPicks': 'Picks gesamt',
      'pickActivityPeakLabel': 'Spitze',
      'pickActivityAvgActive': 'Ø je aktiver Stunde',
      'pickActivityActiveCells': 'Aktive Stunden',
      'pickActivityDaySumHeader': 'Tagessumme',
      'weekdayShortSun': 'So',
      'weekdayShortMon': 'Mo',
      'weekdayShortTue': 'Di',
      'weekdayShortWed': 'Mi',
      'weekdayShortThu': 'Do',
      'weekdayShortFri': 'Fr',
      'weekdayShortSat': 'Sa',
      // Relocation candidates panel
      'relocationEmpty': 'Keine Umlager-Kandidaten gefunden.',
      'relocationDataTitle': 'Konkrete Vorschlaege aus der warehouse.db',
      'relocationUnusedAChip': 'Premium-Plaetze ungenutzt',
      'relocationUnusedANote': 'A-Klasse mit 0 Picks',
      'relocationHotCChip': 'Hochfrequente C-Plaetze',
      'relocationHotCNote': '>= {n} Picks',
      'relocationHighLevelAChip': 'A auf hoher Ebene',
      'relocationHighLevelANote': 'Ebene >= {n}',
      'relocationHotCTitle': 'Hochfrequente C-Plaetze umklassifizieren',
      'relocationHotCSubtitle':
          'Diese Plaetze haben sehr viele Picks, sind aber als C eingestuft.',
      'relocationHighLevelATitle': 'A-Plaetze nach unten holen',
      'relocationHighLevelASubtitle':
          'A-Klasse Plaetze auf hohen Ebenen mit aktiver Pickfrequenz.',
      'relocationUnusedATitle': 'Ungenutzte Premium-Plaetze freimachen',
      'relocationUnusedASubtitle':
          'A-Plaetze ohne Picks - Platz fuer hochfrequente Artikel.',
      'relocationPicksUnit': 'P',
      'relocationMoreCount': '+{n} weitere',
      // Umlagern action reasons
      'umlagernReasonCapacity': 'Auslastung/Stau erhoeht',
      'umlagernReasonHotC': '{n} C-Plaetze mit >= {threshold} Picks',
      'umlagernReasonUnusedA': '{n} A-Plaetze ungenutzt',
      'umlagernReasonOk':
          'Optional: aktuell keine akute Ueberlast erkennbar.',
      'umlagernReasonRecommended': 'Empfohlen: {parts}.',
      // Dashboard sections (new)
      'dashboardSectionOrderVolume': 'Auftragsvolumen',
      'dashboardSectionOrderVolumeSubtitle':
          'Eingehende Auftraege je Tag aus warehouse.db.',
      'dashboardSectionPickActivity': 'Pick-Aktivitaet',
      'dashboardSectionPickActivitySubtitle':
          'Picks pro Wochentag und Stunde.',
      // Tour overlay
      'tourAbcSummaryTitle': 'ABC-Verteilung',
      // DB status chip
      'dbStatusLoading': 'warehouse.db laedt...',
      'dbStatusConnected': 'warehouse.db verbunden',
      'dbStatusError': 'warehouse.db nicht erreichbar',
      // Replenishment / Einlagern panel
      'replenishmentEmpty': 'Keine Replenishment-Kandidaten gefunden.',
      'replenishmentDataTitle': 'Konkrete Vorschlaege aus der warehouse.db',
      'replenishmentUrgentChip': 'Dringend leer',
      'replenishmentUrgentNote': 'Pickplatz, >= {n} Picks',
      'replenishmentOverdueChip': 'Ueberfaellig',
      'replenishmentOverdueNote': '>= {n} Tage leer',
      'replenishmentMediumChip': 'Mittlere Frequenz',
      'replenishmentMediumNote': '{min}-{max} Picks',
      'replenishmentUrgentTitle': 'Dringend nachfuellen',
      'replenishmentUrgentSubtitle':
          'Aktive Pickplaetze sind leer und brauchen sofort Nachschub.',
      'replenishmentOverdueTitle': 'Ueberfaellige Replenishments',
      'replenishmentOverdueSubtitle':
          'Plaetze sind seit Tagen leer trotz hoher Pickfrequenz.',
      'replenishmentMediumTitle': 'Demnaechst nachfuellen',
      'replenishmentMediumSubtitle':
          'Pickplaetze mit mittlerer Frequenz - bald in den Replenishment-Lauf.',
      'replenishmentDaysEmpty': '{n} Tage',
      // Dashboard sections (Einlagern reasons)
      'einlagernReasonUrgent': '{n} dringend leere Pickplaetze',
      'einlagernReasonOverdue':
          '{n} ueberfaellig (>= {days} Tage leer)',
      'einlagernReasonOk':
          'Optional: aktuell keine kritischen Replenishment-Lueckenerkennbar.',
      'einlagernReasonRecommended': 'Empfohlen: {parts}.',
      // Auslagern panel + action reasons
      'retrievalEmpty': 'Keine Auslager-/Bereinigungs-Kandidaten gefunden.',
      'retrievalDataTitle': 'Konkrete Auslager-Vorschlaege aus der warehouse.db',
      'retrievalCriticalChip': 'Kritisch alt',
      'retrievalCriticalNote': '>= {n} Tage ohne Bewegung',
      'retrievalStaleChip': 'Bereinigung noetig',
      'retrievalStaleNote': '>= {n} Tage ohne Bewegung',
      'retrievalObserveChip': 'Beobachten',
      'retrievalObserveNote': '>= {n} Tage ohne Bewegung',
      'retrievalCriticalTitle': 'Sofort auslagern/klaeren',
      'retrievalCriticalSubtitle':
          'Sehr alte Positionen blockieren Flaeche und sollten priorisiert werden.',
      'retrievalStaleTitle': 'Bereinigung einplanen',
      'retrievalStaleSubtitle':
          'Diese Positionen sind alt und sollten in den naechsten Lauf.',
      'retrievalObserveTitle': 'Zur Beobachtung vormerken',
      'retrievalObserveSubtitle':
          'Noch nicht kritisch, aber mit erhoehter Liegedauer.',
      'auslagernReasonCritical':
          '{n} Positionen >= {days} Tage ohne Bewegung',
      'auslagernReasonShare': '{n}% der Plaetze sind Langlieger',
      'auslagernReasonOk':
          'Optional: aktuell keine kritischen Auslager-Signale.',
      'auslagernReasonRecommended': 'Empfohlen: {parts}.',
      // ABC adjustment panel + action reasons
      'abcAdjustEmpty': 'Keine ABC-Artikelkandidaten gefunden.',
      'abcAdjustDataTitle': 'ABC-Umklassifizierungs-Vorschlaege aus warehouse.db',
      'abcAdjustPromoteChip': 'Hochstufen',
      'abcAdjustPromoteNote': 'C mit >= {n} Bewegungen/30T',
      'abcAdjustDemoteChip': 'Runterstufen',
      'abcAdjustDemoteNote': 'A mit <= {picks} Bewegungen oder >= {days} Idle-Tage',
      'abcAdjustReviewChip': 'Review',
      'abcAdjustReviewNote': 'B-Klasse mit auffaelligem Profil',
      'abcAdjustPromoteTitle': 'C-Klasse fuer Hochstufung',
      'abcAdjustPromoteSubtitle':
          'Diese C-Artikel zeigen hohe Aktivitaet und sollten naeher an A/B geprueft werden.',
      'abcAdjustDemoteTitle': 'A-Klasse fuer Runterstufung',
      'abcAdjustDemoteSubtitle':
          'Diese A-Artikel sind inaktiv oder langsam und blockieren Premium-Flaechen.',
      'abcAdjustReviewTitle': 'B-Klasse manuell pruefen',
      'abcAdjustReviewSubtitle':
          'Grenzfaelle zwischen Aktivitaet und Liegedauer fuer den naechsten Zyklus.',
      'abcAdjustMetrics':
          'Klasse {abc} - {moves} Bewegungen/30T - {slots} Plaetze - {days} Tage idle',
      'abcAdjustReasonPromote': '{n} C-Artikel mit >= {picks} Bewegungen',
      'abcAdjustReasonDemote':
          '{n} A-Artikel mit <= {picks} Bewegungen oder >= {days} Idle-Tagen',
      'abcAdjustReasonCShare': 'C-Anteil ist weiterhin hoch',
      'abcAdjustReasonOk':
          'Optional: aktuell keine starken Signale fuer ABC-Umklassifizierung.',
      'abcAdjustReasonRecommended': 'Empfohlen: {parts}.',
      'abcAdjustExecuteLabel': 'ABC-Abgleich starten',
      'abcAdjustExecuteDoneLabel': 'ABC-Abgleich aktualisiert',
      'abcAdjustExecuteSummary':
          '{total} Kandidaten markiert ({promote} hoch, {demote} runter, {review} review).',
      'abcAdjustExecuteSummaryEmpty':
          'Keine Kandidaten erkannt; Verteilung wirkt stabil.',
      // Floor replenishment strategy panel + action reasons
      'floorReplenishmentEmpty': 'Keine Bodenplatz-Nachschubkandidaten gefunden.',
      'floorReplenishmentDataTitle':
          'Bodenplatz-Replenishment aus warehouse.db (Ebene <= {n})',
      'floorReplenishmentUrgentChip': 'Dringend',
      'floorReplenishmentOverdueChip': 'Ueberfaellig',
      'floorReplenishmentMediumChip': 'Demnaechst',
      'floorReplenishmentUrgentTitle': 'Bodenplaetze sofort nachfuellen',
      'floorReplenishmentUrgentSubtitle':
          'Aktive Bodenplaetze mit hoher Picklast sind leer.',
      'floorReplenishmentOverdueTitle': 'Ueberfaellige Bodenplatz-Nachschuebe',
      'floorReplenishmentOverdueSubtitle':
          'Leere Bodenplaetze mit langer Liegedauer priorisieren.',
      'floorReplenishmentMediumTitle': 'Bodenplaetze naechste Welle',
      'floorReplenishmentMediumSubtitle':
          'Mittlere Frequenz fuer den naechsten Nachschublauf vormerken.',
      'floorReplenishmentReasonOverdue': '{n} ueberfaellige Bodenplaetze',
      'floorReplenishmentReasonUrgent': '{n} dringende Bodenplaetze',
      'floorReplenishmentReasonPeakLoad': 'hohe Picklast auf der Flaeche',
      'floorReplenishmentReasonOk':
          'Optional: aktuell keine kritischen Bodenplatz-Signale.',
      'floorReplenishmentReasonRecommended': 'Empfohlen: {parts}.',
      'floorReplenishmentExecuteLabel': 'Bodenplatz-Nachschub starten',
      'floorReplenishmentExecuteDoneLabel': 'Bodenplatz-Nachschub aktualisiert',
      'floorReplenishmentExecuteSummary':
          '{total} Bodenplatz-Kandidaten ({urgent} dringend, {overdue} ueberfaellig, {medium} demnaechst).',
      'floorReplenishmentExecuteSummaryEmpty':
          'Keine Bodenplatz-Kandidaten erkannt.',
      // Putaway strategy panel + action reasons
      'putawayEmpty': 'Keine Einlager-Kandidaten gefunden.',
      'putawayDataTitle': 'Einlager-Vorschlaege aus warehouse.db',
      'putawayFastLaneChip': 'Fast-Lane',
      'putawayFastLaneNote': 'freie A/B bis Ebene {n}',
      'putawayReserveChip': 'Reserve',
      'putawayReserveNote': 'freie C ab Ebene {n}',
      'putawayBlockedChip': 'Gesperrt',
      'putawayBlockedNote': 'vor Einlagerung pruefen',
      'putawayFastLaneTitle': 'Schnelldreher-Ziele',
      'putawayFastLaneSubtitle':
          'Freie A/B-Plaetze in niedrigen Ebenen fuer schnelle Einlagerung.',
      'putawayReserveTitle': 'Reserve-Ziele',
      'putawayReserveSubtitle':
          'Freie C-Plaetze in hoeheren Ebenen fuer langsamere Artikel.',
      'putawayBlockedTitle': 'Gesperrte Plaetze pruefen',
      'putawayBlockedSubtitle':
          'Diese Plaetze sind nicht direkt einlagerfaehig.',
      'putawayTileMeta': 'ABC {abc} - Ebene {level} - Status {status}',
      'putawayReasonInboundBacklog': 'Wareneingang uebersteigt Ausgang',
      'putawayReasonNoFastLane': 'keine freien A/B-Fast-Lane-Plaetze erkannt',
      'putawayReasonBlockedSlots': '{n} gesperrte Plaetze im Sample',
      'putawayReasonOk': 'Optional: Einlagerfluss wirkt aktuell stabil.',
      'putawayReasonRecommended': 'Empfohlen: {parts}.',
      'putawayExecuteLabel': 'Einlagerung planen',
      'putawayExecuteDoneLabel': 'Einlagerung aktualisiert',
      'putawayExecuteSummary':
          '{total} Zielplaetze markiert ({fast} Fast-Lane, {reserve} Reserve, {blocked} gesperrt).',
      'putawayExecuteSummaryEmpty':
          'Keine Einlager-Zielplaetze erkannt.',
    },
    'en': <String, String>{
      'dashboard': 'Dashboard',
      'warehouses': 'Warehouses',
      'viewer': '3D View',
      'profile': 'Profile',
      'tours': 'Tours',
      'controlTower': 'Control Tower',
      'settings': 'Settings',
      'settingsSubtitle':
          'Configure system, language and viewer behavior in one place.',
      'notifications': 'Notifications',
      'controlTowerTitle': 'Live Control Tower',
      'controlTowerSubtitle':
          'Operational overview of utilization, risks and warehouse status.',
      'controlTowerHint':
          'Live overview of utilization, risks and critical alerts.',
      'openControlTower': 'Open Control Tower',
      'controlTowerSystemStatus': 'System status',
      'controlTowerStatusStable': 'Operations stable',
      'controlTowerStatusAttention': 'Attention required',
      'controlTowerUpdatedAt': 'Updated {time}',
      'controlTowerLiveAt': 'Live {time}',
      'controlTowerOnlineLabel': 'Online',
      'controlTowerLimitedLabel': 'Limited',
      'controlTowerMaintenanceLabel': 'Maintenance',
      'controlTowerPriorityTitle': 'Prioritized warehouses',
      'controlTowerPrioritySubtitle':
          'Check high-risk or high-utilization warehouses first.',
      'controlTowerActionsTitle': 'Quick actions',
      'controlTowerActionsSubtitle':
          'Open warehouse list, 3D view and notifications directly.',
      'controlTowerOpenWarehouses': 'Open warehouses',
      'controlTowerOpenViewer': 'Open 3D view',
      'controlTowerOpenTours': 'Open tours',
      'controlTowerOpenNotifications': 'Open notifications',
      'controlTowerOpenTickets': 'Tickets ({count})',
      'controlTowerOverdueTickets': 'SLA overdue tickets',
      'controlTowerAutoEscalations': 'Auto escalations (60 min)',
      'controlTowerAutoEscalationAlert':
          '{count} new auto escalation(s) in the last 5 minutes',
      'controlTowerOpenCriticalTickets': 'Critical tickets',
      'criticalTicketsPanelSubtitle':
          'Direct access to the currently most critical open tickets.',
      'controlTowerAcknowledgeAlert': 'Acknowledge alert',
      'controlTowerAlertAcknowledged': 'Auto escalation alert acknowledged.',
      'controlTowerAcknowledgeAll': 'Acknowledge all',
      'controlTowerEventsOpenCount': '{count} open events',
      'controlTowerEventsOpenEscalatedCount':
          '{open} open | {escalated} escalated',
      'controlTowerNoFilteredEvents': 'No events for the selected filter.',
      'controlTowerAcknowledgeNoPermission':
          'No permission for this action or nothing to acknowledge.',
      'controlTowerEventAcknowledgedMsg': '{title} was acknowledged.',
      'controlTowerAllAcknowledgedMsg': '{count} events were acknowledged.',
      'controlTowerEventEscalatedMsg': '{title} was escalated.',
      'controlTowerEscalateNoPermission':
          'No permission for escalation or already escalated.',
      'controlTowerAuditTitle': 'Activity log',
      'controlTowerAuditSubtitle':
          'Traceable actions in the control tower (acknowledge/escalate).',
      'controlTowerAuditEmpty': 'No actions logged yet.',
      'controlTowerAuditLine': '{action} by {user} ({time})',
      'controlTowerAuditBulkAcknowledgeTitle':
          '{count} events acknowledged in bulk',
      'auditActionAcknowledged': 'Acknowledged',
      'auditActionEscalated': 'Escalated',
      'auditActionAcknowledgedAll': 'Acknowledged all',
      'controlTowerActionPermissionHint':
          'Some actions are restricted for your role.',
      'eventFilterOpen': 'Open',
      'eventFilterAcknowledged': 'Acknowledged',
      'eventFilterEscalated': 'Escalated',
      'eventFilterAll': 'All',
      'eventAcknowledged': 'Acknowledged',
      'eventAcknowledge': 'Acknowledge',
      'eventEscalated': 'Escalated',
      'eventEscalate': 'Escalate',
      'eventSlaDueIn': 'SLA due in {minutes} min',
      'eventSlaBreached': 'SLA +{minutes} min',
      'controlTowerTicketsTitle': 'Control tower tickets',
      'controlTowerTicketsCount':
          '{open} open of {all} tickets | {overdue} SLA overdue',
      'controlTowerTicketsSearchHint': 'Search by ticket content or assignee',
      'controlTowerTicketsEmptyTitle': 'No tickets',
      'controlTowerTicketsEmptyMessage':
          'There are currently no escalation tickets.',
      'criticalTicketsAction': 'Critical tickets',
      'ticketCriticalOnly': 'Critical tickets only',
      'ticketSortLabel': 'Sort order',
      'ticketSortSla': 'SLA first',
      'ticketSortEscalation': 'Escalation first',
      'ticketSortNewest': 'Newest first',
      'ticketSortSlaShort': 'SLA',
      'ticketSortEscalationShort': 'Esc',
      'ticketSortNewestShort': 'New',
      'ticketCriticalBadge': 'Critical',
      'controlTowerTicketUpdateFailed':
          'Ticket could not be updated.',
      'ticketOverdueOnly': 'SLA overdue only',
      'ticketOpenDetails': 'Details',
      'ticketEscalationAll': 'All escalation levels',
      'ticketDetailsTitle': 'Ticket details',
      'ticketDetailsNotFoundTitle': 'Ticket not found',
      'ticketDetailsNotFoundMessage':
          'The ticket could not be loaded or was removed.',
      'ticketTimelineTitle': 'Ticket timeline',
      'ticketNoTimeline': 'No activities yet.',
      'ticketCommentHint': 'Write a comment...',
      'ticketAddComment': 'Send comment',
      'ticketCommentAdded': 'Comment saved.',
      'ticketCommentFailed': 'Comment could not be saved.',
      'ticketUpdatedBy': 'by {user} ({time})',
      'ticketActivityCreated': 'Ticket created',
      'ticketActivityStatusChanged': 'Status changed: {old} -> {new}',
      'ticketActivityEscalationChanged':
          'Escalation level changed: {old} -> {new}',
      'ticketActivityEscalationAuto':
          'SLA breach: Automatic escalation {old} -> {new}',
      'ticketActivityAssigned': 'Assigned to {assignee}',
      'ticketActivityCommented': 'Comment: {comment}',
      'ticketLevelL1': 'L1',
      'ticketLevelL2': 'L2',
      'ticketLevelL3': 'L3',
      'ticketSlaDueIn': 'Ticket SLA due in {minutes} min',
      'ticketSlaBreached': 'Ticket SLA +{minutes} min',
      'ticketSlaBreachedShort': 'SLA overdue by {minutes} min',
      'ticketSlaResolved': 'SLA completed',
      'ticketAssignee': 'Assignee',
      'ticketUnassigned': 'Unassigned',
      'ticketCreatedBy': 'Created by',
      'ticketAssignAction': 'Assign',
      'ticketQuickAssignMeDone': 'Ticket assigned to you.',
      'ticketQuickEscalateL3Done': 'Ticket escalated to L3.',
      'ticketStatusOpen': 'Open',
      'ticketStatusInProgress': 'In progress',
      'ticketStatusResolved': 'Resolved',
      'severity': 'Priority',
      'controlTowerEventsTitle': 'Live events',
      'controlTowerEventsSubtitle':
          'Real-time alerts from warehouse, tours and inventory.',
      'controlTowerNoEvents': 'No critical events at the moment.',
      'eventTypeWarehouse': 'Warehouse',
      'eventTypeTour': 'Tour',
      'eventTypeRamp': 'Ramp',
      'eventTypeInventory': 'Inventory',
      'eventWarehouseTitle': 'Warehouse state',
      'eventWarehouseMaintenance': '{name} is currently in maintenance mode.',
      'eventWarehouseUtilization':
          '{name} reports high utilization ({utilization}%).',
      'eventWarehouseOnline': '{name} is operating normally.',
      'eventTourTitle': 'Tour state',
      'eventTourDelayed': 'Tour {code} ({vehicle}) is delayed.',
      'eventRampTitle': 'Ramp utilization',
      'eventRampLoadLow': 'Tour {code} is only {load}% loaded.',
      'eventNotificationTitle': 'System notification',
      'eventNotificationMessage': '{message}',
      'welcome': 'Welcome, {name}',
      'searchToWarehouse': 'Open warehouse search and filters',
      'filtersReset': 'Reset filters',
      'latestWarehouse': 'Last opened warehouse',
      'badgeNoSelection': 'No selection',
      'badgeFiltered': 'Filtered',
      'badgeAll': 'All',
      'badgeInactive': 'Inactive',
      'badgeReady': 'Ready',
      'badgeEmpty': 'Empty',
      'badgeSaved': 'Saved',
      'badgeAttention': 'Attention',
      'badgeStable': 'Stable',
      'none': 'None',
      'pleaseSelectWarehouse': 'Please select a warehouse',
      'hitsWarehouses': 'Matching warehouses',
      'filteredFrom': 'Filtered from {count} locations',
      'allAvailable': 'All available locations',
      'quick3d': 'Quick 3D access',
      'tourDashboardSubtitle': '{delayed} delayed',
      'notActive': 'Not active',
      'ready': 'Ready',
      'viewerWarehouse': 'Warehouse: {name}',
      'favorites': 'Favorites',
      'favoritesEmpty': 'No favorites yet',
      'favoritesInfo': 'Marked warehouses for quick access',
      'statusDistribution': 'Status distribution',
      'statusFilter': 'Status filter',
      'onlineCount': '{count} online',
      'limitedCount': '{count} limited',
      'maintenanceCount': '{count} maintenance',
      'selectedCount': '{count} warehouses in current selection',
      'searchHint': 'Search by warehouse name or location',
      'all': 'All',
      'warehousesCount': '{shown} of {all} locations',
      'noWarehousesFound': 'No warehouses found',
      'adjustFilters': 'Adjust search or status filters.',
      'noWarehouseData': 'No warehouse data available right now.',
      'open3d': '3D View',
      'removeFavorite': 'Remove favorite',
      'markFavorite': 'Mark as favorite',
      'selectedWarehouseMsg': '{name} selected.',
      'favoriteAddedMsg': '{name} added to favorites.',
      'favoriteRemovedMsg': '{name} removed from favorites.',
      'close': 'Close',
      'open3dView': 'Open 3D view',
      'zones': 'Zones',
      'id': 'ID',
      'location': 'Location',
      'status': 'Status',
      'name': 'Name',
      'splashSubtitle': 'Digital warehouse visualization',
      'loadingA': 'Initializing warehouse data...',
      'loadingB': 'Connecting viewer components...',
      'loadingC': 'Preparing dashboard...',
      'login': 'Sign in',
      'email': 'Email',
      'password': 'Password',
      'forgotPassword': 'Forgot password',
      'demoLogin': 'Demo login',
      'enterEmail': 'Enter email',
      'enterPassword': 'Enter password',
      'loginSuccess': 'Successfully signed in.',
      'loginMissing': 'Please enter email and password.',
      'passwordResetInactive': 'Password reset is not active in this MVP.',
      'emptyViewerTitle': 'No warehouse selected',
      'emptyViewerMessage':
          'Select a warehouse from the list first to start the 3D view.',
      'toWarehouseList': 'Open warehouse list',
      'toDashboard': 'Go to dashboard',
      'adapter': 'Adapter: {name}',
      'viewerCanvasTitle': '3D warehouse view',
      'viewerFullscreenTour': 'Full-screen tour',
      'viewerControlsHint': 'Swipe to rotate, two fingers to zoom, tap to focus',
      'viewerQuickActionsTitle': 'Quick actions',
      'viewerQuickActionsHint': 'Controls next to the model',
      'viewerReset': 'Reset view',
      'viewerShowZones': 'Show zones',
      'viewerHideZones': 'Hide zones',
      'viewerStartTour': 'Start tour',
      'viewerPauseTour': 'Pause tour',
      'viewerTourHeader': '{name} - {status} - choose Orbit/FP',
      'viewerLegendShow': 'Show legend',
      'viewerLegendHide': 'Hide legend',
      'viewerLegendTitle': 'Legend',
      'viewerLegendHeatmapOn': 'Heatmap active on racks',
      'viewerLegendHeatmapOff': 'Heatmap currently hidden',
      'viewerShowHeatmap': 'Show heatmap',
      'viewerHideHeatmap': 'Hide heatmap',
      'storageLocationTitle': 'Storage location',
      'storageLocationSubtitle':
          'Target rack, level and slot precisely.',
      'storageLocationRackLabel': 'Rack',
      'storageLocationLevelLabel': 'Level',
      'storageLocationSlotLabel': 'Slot',
      'storageLocationSlotHelper': '1 to {max}',
      'storageLocationSlotInvalid':
          'Please enter a valid slot number.',
      'storageLocationSummary':
          'Selection: Rack {rack} · Level {level} · Slot {slot}',
      'storageLocationFocusAction': 'Show location',
      'storageLocationFocusToast':
          'Focus set: Rack {rack}, Level {level}, Slot {slot}',
      'storageLocationCodeLabel': 'Location code',
      'storageLocationCodeHint': 'e.g. R01-E03-F010',
      'storageLocationCodeApply': 'Apply code',
      'storageLocationCodeInvalid':
          'Please enter a valid format like R01-E03-F010.',
      'storageLocationSamplesTitle': 'Sample storage locations',
      'storageLocationSamplesSubtitle': 'Small sample pulled from warehouse.db.',
      'storageLocationSamplesEmpty':
          'No sample storage locations loaded yet.',
      'storageLocationSamplesCount': '{count} of {total}',
      'storageLocationVisibleCount': '{count} of {total} visible',
      'storageLocationShowMore': 'Show more',
      'storageLocationShowLess': 'Show less',
      'storageLocationFilterLabel': 'Search storage location',
      'storageLocationFilterHint': 'Rack, level, slot or code',
      'storageLocationFilterClear': 'Clear filter',
      'storageLocationSuggestionsTitle': 'Suggestions',
      'storageLocationSortAbc': 'Sort: ABC',
      'storageLocationSortRack': 'Sort: Rack',
      'storageLocationViewInViewer': 'Show in viewer',
      'storageLocationDetailsTitle': 'Storage location details',
      'storageLocationDetailsSubtitle':
          'Selected location with detail fields.',
      'storageLocationDetailsEmpty':
          'Select a storage location to see details.',
      'storageLocationFieldPlace': 'Place ID',
      'storageLocationFieldArea': 'Area',
      'storageLocationFieldAbc': 'ABC class',
      'storageLocationFieldStatus': 'Status',
      'storageLocationFieldRack': 'Rack',
      'storageLocationFieldLevel': 'Level',
      'storageLocationFieldSlot': 'Slot',
      'warehouseAreaLabel': 'Area',
      'warehouseStatusShort': 'Status',
      'heatmapMetricLabel': 'Heatmap metric',
      'heatmapMetricChangedMsg': 'Heatmap metric: {metric}',
      'heatmapLegendTitle': 'Heatmap: {metric}',
      'heatmapActiveState': 'Heatmap active ({metric})',
      'heatmapInactiveState': 'Heatmap off',
      'heatmapMetricUtilization': 'Utilization',
      'heatmapMetricPickRate': 'Pick rate',
      'heatmapMetricCongestion': 'Congestion',
      'heatmapMetricAbcA': 'A share',
      'heatmapOverviewTitle': 'Heatmap overview',
      'heatmapOverviewSubtitle': 'Quick view of top zone and severity levels.',
      'heatmapTopZoneLabel': 'Top zone',
      'heatmapAverageLabel': 'Average: {value}',
      'heatmapSeverityHigh': 'High',
      'heatmapSeverityMedium': 'Medium',
      'heatmapSeverityLow': 'Low',
      'heatmapFocusTopZone': 'Focus top zone',
      'heatmapOpenTopZoneDetails': 'Top zone details',
      'heatmapZoneTypeLabel': 'Zone type',
      'heatmapZoneTypeInbound': 'Inbound',
      'heatmapZoneTypePicking': 'Picking',
      'heatmapZoneTypeShipping': 'Shipping',
      'heatmapZoneTypeStorage': 'Storage',
      'heatmapZoneTypeOther': 'Other',
      'heatmapNoZonesForType': 'No zones available for the selected type.',
      'heatmapCriticalZonesTitle': 'Top problem zones',
      'heatmapLiveBadge': 'Live',
      'heatmapAutoFocusActive': 'Auto focus active',
      'heatmapLivePause': 'Pause live mode',
      'heatmapLiveStart': 'Start live mode',
      'heatmapAutoFocusPause': 'Pause auto focus',
      'heatmapAutoFocusStart': 'Start auto focus',
      'heatmapNoZonesForSelectedFilters':
          'No zones in the selected priority range.',
      'zonesVisible': 'Zones visible',
      'zonesHidden': 'Zones hidden',
      'tourActive': 'Tour active',
      'tourPaused': 'Tour paused',
      'resets': 'Resets: {count}',
      'zonesHiddenMsg': 'Zone overlay hidden.',
      'tourPausedMsg': 'Tour paused.',
      'viewerNoModelZonesForFocus': 'No model zones available for focus.',
      'viewerFocusCriticalZoneMsg': 'Focus set to critical zone: {zone}',
      'viewerFocusCriticalZoneAction': 'Focus critical zone',
      'role': 'Role: {role}',
      'logout': 'Logout',
      'language': 'Language',
      'languageGerman': 'German',
      'languageEnglish': 'English',
      'notificationsToggle': 'Notifications',
      'notificationsDemoSetting': 'Local demo setting',
      'settingsAutoSaveStatus': 'Automatic saving',
      'settingsLastSavedAt': 'Last saved: {time}',
      'settingsNeverSaved': 'No changes saved yet',
      'settingsTransferTitle': 'Transfer settings',
      'settingsTransferSubtitle':
          'Export or import local settings as JSON.',
      'settingsExportAction': 'Export',
      'settingsImportAction': 'Import',
      'settingsExportCopied': 'Settings JSON copied to clipboard.',
      'settingsImportTitle': 'Import settings',
      'settingsImportHint': 'Paste JSON...',
      'settingsImportPasteFromClipboard': 'Paste from clipboard',
      'settingsImportApply': 'Apply import',
      'settingsImportSuccess': 'Settings imported successfully.',
      'settingsImportFailed': 'Import failed. Please check JSON format.',
      'settingsImportValidationHint':
          'Paste a JSON object only, e.g. {"languageCode":"en"}.',
      'settingsImportJsonValid': 'JSON format looks valid.',
      'settingsImportJsonInvalid':
          'Invalid JSON. Please paste a valid JSON object.',
      'settingsImportClipboardEmpty': 'Clipboard is empty or has no text.',
      'settingsImportClipboardLoaded': 'Clipboard content inserted into import field.',
      'darkMode': 'Dark mode',
      'themeSwitch': 'Material 3 theme switch',
      'viewerIntegration': 'Viewer integration',
      'autoEscalationSettingsTitle': 'Auto escalation rules',
      'autoEscalationSettingsSubtitle':
          'Defines when SLA-breached tickets are automatically escalated.',
      'autoEscalationPresetLabel': 'Preset',
      'autoEscalationPresetCurrent': 'Active: {preset}',
      'autoEscalationPresetConservative': 'Conservative',
      'autoEscalationPresetStandard': 'Standard',
      'autoEscalationPresetAggressive': 'Aggressive',
      'autoEscalationPresetCustom': 'Custom',
      'autoEscalationResetRules': 'Reset rules to default',
      'autoEscalationResetDone':
          'Auto escalation rules reset to standard.',
      'autoEscalationFirstStepValue':
          'L1 -> L2 after {minutes} min SLA breach',
      'autoEscalationSecondStepValue':
          'L2 -> L3 after {minutes} min SLA breach',
      'appVersion': 'App version',
      'markAllRead': 'Mark all read',
      'noNotifications': 'No notifications',
      'noNotificationsMsg': 'There are no notifications at the moment.',
      'remove': 'Remove',
      'justNow': 'just now',
      'minutesAgo': '{count} min ago',
      'hoursAgo': '{count} h ago',
      'daysAgo': '{count} day(s) ago',
      'statusOnline': 'Online',
      'statusLimited': 'Limited',
      'statusMaintenance': 'Maintenance',
      'roleAdmin': 'Admin',
      'roleOperator': 'Operator',
      'roleViewer': 'Viewer',
      'viewerTypeNative': 'Native placeholder',
      'viewerTypeUnity': 'Unity',
      'viewerTypeWebView': 'WebView',
      'viewerTypeNativeDesc': 'Direct Flutter UI as demo surface',
      'viewerTypeUnityDesc': 'Prepared for Unity-based 3D viewer',
      'viewerTypeWebViewDesc': 'Prepared for web-based 3D viewer',
      'severityInfo': 'Info',
      'severityWarning': 'Warning',
      'severityCritical': 'Critical',
      'healthStable': 'Stable',
      'healthWatch': 'Watch',
      'healthCritical': 'Critical',
      'priorityScoreBreakdownTitle': 'Score breakdown',
      'priorityScoreFactorStatus': 'Status factor',
      'priorityScoreFactorUtilization': 'Utilization factor',
      'priorityScoreFactorFlow': 'Flow factor',
      'priorityScoreFactorOperations': 'Operational risk factor',
      'priorityScoreSummary':
          'S {status} | U {utilization} | F {flow} | O {operations}',
      'priorityScoreSummaryCompact':
          'S{status} U{utilization} F{flow} O{operations}',
      'dashboardAbcTitle': 'ABC analysis (current selection)',
      'dashboardAbcSubtitle':
          'A: Fast movers | B: Mid movers | C: Slow movers',
      'kpiAShare': 'A share',
      'kpiBShare': 'B share',
      'kpiCShare': 'C share',
      'topWarehousesTitle': 'Top warehouses by utilization',
      'topWarehousesSubtitle':
          'Quick view of capacity, articles and ABC distribution.',
      'searchFilterSummaryBoth': 'Search: "{query}" | Status: {status}',
      'searchFilterSummaryQuery': 'Search: "{query}"',
      'searchFilterSummaryStatus': 'Status: {status}',
      'noFiltersActive': 'No active filters',
      'noExportPermission': 'Your role is not allowed to export reports.',
      'reportExported': 'Report exported: warehouse_report_{date}.csv ({count} warehouses)',
      'performanceTitle': 'Warehouse performance',
      'performanceSubtitle':
          'Overall utilization across all currently filtered warehouses.',
      'kpiUtilization': 'Utilization',
      'kpiOccupied': 'Occupied',
      'kpiFree': 'Free',
      'kpiTotalSlots': 'Total slots',
      'kpiArticles': 'Articles',
      'exportReport': 'Export daily report',
      'exportUnavailable': 'Export unavailable',
      'warehouseTitle': 'Warehouses',
      'createWarehouse': 'New warehouse',
      'warehouseCreateFailed': 'Warehouse could not be created via API.',
      'warehousesSyncAction': 'Sync with backend',
      'warehousesSyncError': 'Backend sync failed: {error}',
      'retry': 'Retry',
      'refreshNow': 'Refresh',
      'backendOnline': 'Backend online',
      'backendOffline': 'Backend offline',
      'backendIssue': 'Backend warning',
      'lastSyncShort': 'Sync: {time}',
      'lastSyncUnknown': 'Sync: -',
      'viewerDataUpdated': 'Warehouse data updated.',
      'newWarehouseTitle': 'Create warehouse',
      'warehouseNameLabel': 'Warehouse name',
      'warehouseLocationLabel': 'Location',
      'warehouseZonesLabel': 'Zones',
      'warehouseDescriptionLabel': 'Description',
      'warehouseStatusLabel': 'Status',
      'warehouseBaseData': 'Base data',
      'warehouseLayoutData': 'Warehouse dimensions',
      'warehouseRackingData': 'Racking structure',
      'warehouseZonesData': 'Zones',
      'warehouseLengthLabel': 'Length (m)',
      'warehouseWidthLabel': 'Width (m)',
      'warehouseHeightLabel': 'Height (m)',
      'rackRowsLabel': 'Rack rows',
      'rackLengthLabel': 'Rack length (m)',
      'rackWidthLabel': 'Rack width (m)',
      'rackLevelsLabel': 'Rack levels',
      'aisleWidthLabel': 'Aisle width (m)',
      'zonesInputLabel': 'Zones (comma/new line separated)',
      'zonesInputHint': 'e.g. inbound, picking, dispatch',
      'zonesInputInvalid': 'Please provide at least one zone.',
      'warehouseCapacityData': 'Capacity data',
      'warehouseFlowData': 'Flow data',
      'warehouseAbcData': 'ABC data',
      'totalStorageSlotsLabel': 'Total slots',
      'occupiedStorageSlotsLabel': 'Occupied slots',
      'articleCountLabel': 'Article count',
      'inboundPerDayLabel': 'Inbound / day',
      'throughputPerDayLabel': 'Throughput / day',
      'pickRatePerHourLabel': 'Pick rate / hour',
      'aCountLabel': 'A items',
      'bCountLabel': 'B items',
      'cCountLabel': 'C items',
      'enterWarehouseName': 'Enter warehouse name',
      'enterWarehouseLocation': 'Enter location',
      'zoneCountInvalid': 'Please enter at least 1 zone',
      'invalidNumber': 'Please enter a valid number',
      'occupiedMustBeWithinTotal': 'Occupied slots must be <= total slots',
      'cancel': 'Cancel',
      'warehouseCreatedMsg': '{name} was created.',
      'warehouseUpdatedMsg': '{name} was updated.',
      'warehouseDeletedMsg': '{name} was deleted.',
      'warehouseCreateNoPermission':
          'Your role is not allowed to create warehouses.',
      'warehouseEditNoPermission':
          'Your role is not allowed to edit this warehouse.',
      'warehouseDeleteNoPermission':
          'Your role is not allowed to delete this warehouse.',
      'warehouseDeleteFailed': 'Warehouse could not be deleted.',
      'viewerRoleNoFavorites':
          'Favorites cannot be changed in viewer role.',
      'warehouseNotFound': 'Warehouse not found',
      'warehouseNotFoundMessage':
          'The requested warehouse could not be loaded.',
      'warehouseIdLabel': 'Warehouse ID',
      'articlesTotal': 'Total articles',
      'removeFavoriteShort': 'Remove favorite',
      'saveFavorite': 'Save as favorite',
      'editWarehouse': 'Edit warehouse',
      'deleteWarehouse': 'Delete warehouse',
      'editWarehouseTitle': 'Edit warehouse',
      'deleteWarehouseTitle': 'Delete warehouse',
      'deleteWarehousePrompt': 'Do you really want to delete warehouse "{name}"?',
      'deleteWarehouseWarning': 'This action cannot be undone.',
      'confirmDelete': 'Delete',
      'saveChanges': 'Save changes',
      'changeWarehouseStatus': 'Change status',
      'warehouseStatusUpdatedMsg': '{name} status: {status}',
      'warehouseKpiTitle': 'Performance metrics',
      'tabOverview': 'Overview',
      'tabZones': 'Zones',
      'tabPerformance': 'Performance',
      'tabOperations': 'Operations',
      'tabAbc': 'ABC',
      'tabTours': 'Tours',
      'tabHistory': 'History',
      'warehouseOperationsTitle': 'Operational metrics',
      'warehouseOperationsSubtitle':
          'Dock usage, SLA and slot mix for day-to-day operations.',
      'opsDockActive': 'Active docks',
      'opsDockUtilization': 'Dock utilization',
      'opsBlockedSlots': 'Blocked slots',
      'opsReservedSlots': 'Reserved slots',
      'opsAvgDwell': 'Average dwell time',
      'opsSlaCurrent': 'SLA current',
      'opsSlaTarget': 'SLA target',
      'opsSlotMixTitle': 'Slot mix',
      'opsHighBaySlots': 'High-bay',
      'opsBlockStorageSlots': 'Block storage',
      'opsShuttleSlots': 'Shuttle',
      'opsFloorStorageSlots': 'Floor storage',
      'opsColdZones': 'Cold zones',
      'opsAmbientZones': 'Ambient zones',
      'opsHazardousZones': 'Hazardous zones',
      'opsSafetyIncidents': 'Safety incidents (month)',
      'opsQualityHolds': 'Quality holds',
      'warehouseToursTitle': 'Warehouse tours',
      'warehouseToursSubtitle': '{count} tours are currently assigned.',
      'warehouseTourLine':
          '{driver} | {status} | Stops: {stops} | Load: {load}%',
      'warehouseToursEmpty': 'No tours are currently assigned to this warehouse.',
      'openTours': 'Open tours',
      'historyTitle': 'History & events',
      'historySubtitle':
          'Timeline of key operational events for this warehouse.',
      'historySearchHint': 'Search events',
      'historyFilterAll': 'All',
      'historyFilterAlert': 'Alert',
      'historyFilterInventory': 'Inventory',
      'historyFilterPerformance': 'Performance',
      'historyFilterMaintenance': 'Maintenance',
      'historyNoResults': 'No events for the current filter.',
      'historyAlertTitle': 'Status event',
      'historyInventoryTitle': 'Inventory run',
      'historyPerformanceTitle': 'Performance snapshot',
      'historyMaintenanceTitle': 'Maintenance log',
      'historyAlertMaintenanceMsg': 'Maintenance status active for {name}.',
      'historyAlertHealthyMsg': 'Status check successful for {name}.',
      'historyInventoryMsg':
          'Inventory run finished: {count} items processed.',
      'historyPerformanceMsg':
          'Throughput today: {throughput}/day | Pick rate: {pick}/h',
      'historyMaintenanceMsg':
          'Maintenance window for conveyor system documented.',
      'warehouseKpiSubtitle':
          'Capacity, utilization, inbound and throughput at a glance.',
      'kpiOccupiedSlots': 'Occupied slots',
      'kpiFreeSlots': 'Free slots',
      'kpiInboundPerDay': 'Inbound / day',
      'kpiThroughputPerDay': 'Throughput / day',
      'kpiPickRatePerHour': 'Pick rate / hour',
      'warehouseAbcTitle': 'Warehouse ABC analysis',
      'warehouseAbcSubtitle':
          'Distribution of article classes A/B/C for {count} positions.',
      'zoneAnalysisTitle': 'Zone analysis',
      'zoneAnalysisSubtitle':
          'ABC and performance metrics per zone for operations.',
      'zoneSlotsArticlesLine':
          'Slots {occupied}/{total} | Articles {articles}',
      'zoneFlowLine':
          'Inbound {inbound}/day | Throughput {throughput}/day | Pick rate {pick}/h',
      'viewerRoleHint':
          'Note: Viewer role has control actions disabled.',
      'adapterStatusActive': 'Active',
      'adapterStatusPrepared': 'Prepared',
      'nativeViewerName': 'Native placeholder viewer',
      'unityViewerName': 'Unity adapter',
      'webViewViewerName': 'WebView adapter',
      'nativePlaceholderTitle': '3D model placeholder',
      'nativePlaceholderSubtitle':
          'The model for {name} will be loaded here later.',
      'unityPlaceholderTitle': 'Unity integration prepared',
      'unityPlaceholderSubtitle':
          'Interface is ready. Unity view will be embedded here later.',
      'webViewPlaceholderTitle': 'WebView integration prepared',
      'webViewPlaceholderSubtitle':
          'A web-based 3D viewer will be loaded here later.',
      'adapterResetMessage': 'View for {name} was reset.',
      'adapterShowZonesMessage':
          '{count} zones shown for {name}.',
      'adapterStartTourMessage': 'Tour through {name} started.',
      'adapterHeatmapShownMessage':
          'Heatmap "{metric}" enabled for {name}.',
      'adapterHeatmapHiddenMessage': 'Heatmap hidden for {name}.',
      'viewerGenerationTitle': 'Automatic warehouse view',
      'viewerModelStateAvailable': 'Generated',
      'viewerModelStateMissing': 'Not generated',
      'viewerGenerationSubtitleReady':
          'The simplified warehouse view is available and shown below.',
      'viewerGenerationSubtitleMissing':
          'Generate a simplified warehouse view from structured data.',
      'viewerGenerateAction': 'Generate view',
      'viewerModelGeneratedAt': 'Last generated: {time}',
      'viewerModelGeneratedSuccess': 'Warehouse view generated successfully.',
      'viewerModelGeneratedError': 'Warehouse view generation failed.',
      'viewerBackendOfflineInfo':
          'Backend currently unreachable. The app is using local data (offline mode).',
      'viewerGeneratedCanvasTitle': 'Generated warehouse view',
      'viewerModelShelves': 'Rack grid',
      'viewerGeneratedCanvasSubtitle':
          'Schematic representation for {name} based on layout data.',
      'unityAdapterInactive': 'Unity adapter is prepared but not active yet.',
      'unityZonesPending': 'Unity zone overlay will be available after integration.',
      'unityTourPending': 'Unity tour will be available after integration.',
      'unityHeatmapPending': 'Unity heatmap will be available after integration.',
      'webViewAdapterInactive': 'WebView adapter is prepared but not active yet.',
      'webViewZonesPending': 'WebView zone overlay will be available after integration.',
      'webViewTourPending': 'WebView tour will be available after integration.',
      'webViewHeatmapPending': 'WebView heatmap will be available after integration.',
      'toursTitle': 'Transport tours',
      'toursCount': '{shown} of {all} tours',
      'tourKpiActive': 'Active',
      'tourKpiDelayed': 'Delayed',
      'tourKpiCompleted': 'Completed',
      'tourSearchHint': 'Search by code, driver or vehicle',
      'noToursFound': 'No tours found',
      'noToursData': 'No tour data available right now.',
      'tourProgressLine': 'Progress {percent}% ({completed}/{total} stops)',
      'tourLoadLine': 'Load {load}% | ETA {eta}',
      'tourStopsAction': 'Stops',
      'warehouseAction': 'Warehouse',
      'tourStopsTitle': 'Stops for {code}',
      'tourStopsSubtitle': '{count} planned stops',
      'tourStopEta': 'Planned arrival',
      'tourStatusPlanned': 'Planned',
      'tourStatusLoading': 'Loading',
      'tourStatusInTransit': 'In transit',
      'tourStatusDelayed': 'Delayed',
      'tourStatusCompleted': 'Completed',
      'tourStopPending': 'Pending',
      'tourStopArrived': 'Arrived',
      'tourStopUnloaded': 'Unloaded',
      'roleDemo': 'User role (demo)',
      'roleDemoHint':
          'Viewer role: read-only | Operator/Admin: full actions',
      'accessDeniedTitle': 'Access denied',
      'accessDeniedMessage':
          'Your role is not allowed to open this page ({path}).',
      // Order volume card
      'orderVolumeTitle': 'Order volume',
      'orderVolumeSubtitle': 'Incoming orders per day from warehouse.db.',
      'orderVolumeEmpty': 'No order data found.',
      'orderVolumePerDay': 'Avg/day',
      'orderVolumeOrdersUnit': 'orders',
      'orderVolumePeak': 'Peak',
      'orderVolumePositionsTotal': 'Total positions',
      // Pick activity heatmap
      'pickActivityTitle': 'Pick activity by hour',
      'pickActivitySubtitle': 'Picks per weekday and hour from warehouse.db.',
      'pickActivityRange': 'Picks per weekday and hour · {from} – {to}',
      'pickActivityEmpty': 'No pick data found.',
      'pickActivityTooltip': '{day} {hour}:00 · {picks} picks',
      'pickActivityTotalPicks': 'Total picks',
      'pickActivityPeakLabel': 'Peak',
      'pickActivityAvgActive': 'Avg / active hour',
      'pickActivityActiveCells': 'Active hours',
      'pickActivityDaySumHeader': 'Day total',
      'weekdayShortSun': 'Sun',
      'weekdayShortMon': 'Mon',
      'weekdayShortTue': 'Tue',
      'weekdayShortWed': 'Wed',
      'weekdayShortThu': 'Thu',
      'weekdayShortFri': 'Fri',
      'weekdayShortSat': 'Sat',
      // Relocation candidates panel
      'relocationEmpty': 'No relocation candidates found.',
      'relocationDataTitle': 'Concrete suggestions from warehouse.db',
      'relocationUnusedAChip': 'Premium spots unused',
      'relocationUnusedANote': 'A class with 0 picks',
      'relocationHotCChip': 'High-pick C spots',
      'relocationHotCNote': '>= {n} picks',
      'relocationHighLevelAChip': 'A on high level',
      'relocationHighLevelANote': 'Level >= {n}',
      'relocationHotCTitle': 'Reclassify high-pick C spots',
      'relocationHotCSubtitle':
          'These spots have many picks but are classified as C.',
      'relocationHighLevelATitle': 'Move A spots to lower levels',
      'relocationHighLevelASubtitle':
          'A-class spots on high levels with active pick frequency.',
      'relocationUnusedATitle': 'Free up unused premium spots',
      'relocationUnusedASubtitle':
          'A spots without picks - room for high-pick articles.',
      'relocationPicksUnit': 'P',
      'relocationMoreCount': '+{n} more',
      // Umlagern action reasons
      'umlagernReasonCapacity': 'Utilization/congestion elevated',
      'umlagernReasonHotC': '{n} C spots with >= {threshold} picks',
      'umlagernReasonUnusedA': '{n} A spots unused',
      'umlagernReasonOk': 'Optional: no acute overload detected.',
      'umlagernReasonRecommended': 'Recommended: {parts}.',
      // Dashboard sections (new)
      'dashboardSectionOrderVolume': 'Order volume',
      'dashboardSectionOrderVolumeSubtitle':
          'Incoming orders per day from warehouse.db.',
      'dashboardSectionPickActivity': 'Pick activity',
      'dashboardSectionPickActivitySubtitle':
          'Picks per weekday and hour.',
      // Tour overlay
      'tourAbcSummaryTitle': 'ABC distribution',
      // DB status chip
      'dbStatusLoading': 'Loading warehouse.db...',
      'dbStatusConnected': 'warehouse.db connected',
      'dbStatusError': 'warehouse.db unreachable',
      // Replenishment / Einlagern panel
      'replenishmentEmpty': 'No replenishment candidates found.',
      'replenishmentDataTitle': 'Concrete suggestions from warehouse.db',
      'replenishmentUrgentChip': 'Empty urgent',
      'replenishmentUrgentNote': 'Pick spot, >= {n} picks',
      'replenishmentOverdueChip': 'Overdue',
      'replenishmentOverdueNote': '>= {n} days empty',
      'replenishmentMediumChip': 'Medium frequency',
      'replenishmentMediumNote': '{min}-{max} picks',
      'replenishmentUrgentTitle': 'Refill urgently',
      'replenishmentUrgentSubtitle':
          'Active pick spots are empty and need replenishment now.',
      'replenishmentOverdueTitle': 'Overdue replenishments',
      'replenishmentOverdueSubtitle':
          'Spots have been empty for days despite high pick activity.',
      'replenishmentMediumTitle': 'Refill soon',
      'replenishmentMediumSubtitle':
          'Pick spots with medium frequency - schedule for next run.',
      'replenishmentDaysEmpty': '{n} days',
      // Dashboard sections (Einlagern reasons)
      'einlagernReasonUrgent': '{n} urgent empty pick spots',
      'einlagernReasonOverdue': '{n} overdue (>= {days} days empty)',
      'einlagernReasonOk':
          'Optional: no critical replenishment gaps detected.',
      'einlagernReasonRecommended': 'Recommended: {parts}.',
      // Retrieval panel + action reasons
      'retrievalEmpty': 'No retrieval/cleanup candidates found.',
      'retrievalDataTitle': 'Concrete retrieval suggestions from warehouse.db',
      'retrievalCriticalChip': 'Critical aged',
      'retrievalCriticalNote': '>= {n} days without movement',
      'retrievalStaleChip': 'Cleanup needed',
      'retrievalStaleNote': '>= {n} days without movement',
      'retrievalObserveChip': 'Observe',
      'retrievalObserveNote': '>= {n} days without movement',
      'retrievalCriticalTitle': 'Retrieval/clarification now',
      'retrievalCriticalSubtitle':
          'Very old positions block capacity and should be prioritized.',
      'retrievalStaleTitle': 'Plan cleanup run',
      'retrievalStaleSubtitle':
          'These positions are stale and should be handled in the next wave.',
      'retrievalObserveTitle': 'Mark for observation',
      'retrievalObserveSubtitle':
          'Not critical yet, but with increased dwell time.',
      'auslagernReasonCritical': '{n} positions >= {days} days without movement',
      'auslagernReasonShare': '{n}% of slots are slow movers',
      'auslagernReasonOk':
          'Optional: no critical retrieval signals detected.',
      'auslagernReasonRecommended': 'Recommended: {parts}.',
      // ABC adjustment panel + action reasons
      'abcAdjustEmpty': 'No ABC article candidates found.',
      'abcAdjustDataTitle': 'ABC reclassification suggestions from warehouse.db',
      'abcAdjustPromoteChip': 'Promote',
      'abcAdjustPromoteNote': 'C with >= {n} movements/30d',
      'abcAdjustDemoteChip': 'Demote',
      'abcAdjustDemoteNote':
          'A with <= {picks} movements or >= {days} idle days',
      'abcAdjustReviewChip': 'Review',
      'abcAdjustReviewNote': 'B class with notable profile',
      'abcAdjustPromoteTitle': 'Promote C-class candidates',
      'abcAdjustPromoteSubtitle':
          'These C articles show high activity and should be reviewed towards A/B.',
      'abcAdjustDemoteTitle': 'Demote A-class candidates',
      'abcAdjustDemoteSubtitle':
          'These A articles are inactive or slow and block premium space.',
      'abcAdjustReviewTitle': 'Review B-class manually',
      'abcAdjustReviewSubtitle':
          'Borderline cases between movement and dwell time for the next cycle.',
      'abcAdjustMetrics':
          'Class {abc} - {moves} movements/30d - {slots} slots - {days} idle days',
      'abcAdjustReasonPromote': '{n} C articles with >= {picks} movements',
      'abcAdjustReasonDemote':
          '{n} A articles with <= {picks} movements or >= {days} idle days',
      'abcAdjustReasonCShare': 'C-share remains elevated',
      'abcAdjustReasonOk':
          'Optional: no strong ABC reclassification signal detected.',
      'abcAdjustReasonRecommended': 'Recommended: {parts}.',
      'abcAdjustExecuteLabel': 'Start ABC alignment',
      'abcAdjustExecuteDoneLabel': 'ABC alignment refreshed',
      'abcAdjustExecuteSummary':
          '{total} candidates marked ({promote} up, {demote} down, {review} review).',
      'abcAdjustExecuteSummaryEmpty':
          'No candidates detected; distribution looks stable.',
      // Floor replenishment strategy panel + action reasons
      'floorReplenishmentEmpty': 'No floor-slot replenishment candidates found.',
      'floorReplenishmentDataTitle':
          'Floor-slot replenishment from warehouse.db (level <= {n})',
      'floorReplenishmentUrgentChip': 'Urgent',
      'floorReplenishmentOverdueChip': 'Overdue',
      'floorReplenishmentMediumChip': 'Soon',
      'floorReplenishmentUrgentTitle': 'Refill floor slots now',
      'floorReplenishmentUrgentSubtitle':
          'Active floor slots with high pick load are empty.',
      'floorReplenishmentOverdueTitle': 'Overdue floor-slot replenishments',
      'floorReplenishmentOverdueSubtitle':
          'Prioritize empty floor slots with long empty duration.',
      'floorReplenishmentMediumTitle': 'Next-wave floor slots',
      'floorReplenishmentMediumSubtitle':
          'Queue medium-frequency slots for the next replenishment run.',
      'floorReplenishmentReasonOverdue': '{n} overdue floor slots',
      'floorReplenishmentReasonUrgent': '{n} urgent floor slots',
      'floorReplenishmentReasonPeakLoad': 'high pick load on floor area',
      'floorReplenishmentReasonOk':
          'Optional: no critical floor-slot signal detected.',
      'floorReplenishmentReasonRecommended': 'Recommended: {parts}.',
      'floorReplenishmentExecuteLabel': 'Start floor replenishment',
      'floorReplenishmentExecuteDoneLabel': 'Floor replenishment refreshed',
      'floorReplenishmentExecuteSummary':
          '{total} floor-slot candidates ({urgent} urgent, {overdue} overdue, {medium} soon).',
      'floorReplenishmentExecuteSummaryEmpty':
          'No floor-slot candidates detected.',
      // Putaway strategy panel + action reasons
      'putawayEmpty': 'No putaway candidates found.',
      'putawayDataTitle': 'Putaway suggestions from warehouse.db',
      'putawayFastLaneChip': 'Fast lane',
      'putawayFastLaneNote': 'free A/B up to level {n}',
      'putawayReserveChip': 'Reserve',
      'putawayReserveNote': 'free C from level {n}',
      'putawayBlockedChip': 'Blocked',
      'putawayBlockedNote': 'check before putaway',
      'putawayFastLaneTitle': 'Fast-mover targets',
      'putawayFastLaneSubtitle':
          'Free low-level A/B slots for quick inbound putaway.',
      'putawayReserveTitle': 'Reserve targets',
      'putawayReserveSubtitle':
          'Free higher-level C slots for slower-moving items.',
      'putawayBlockedTitle': 'Review blocked slots',
      'putawayBlockedSubtitle':
          'These slots are not directly available for putaway.',
      'putawayTileMeta': 'ABC {abc} - Level {level} - Status {status}',
      'putawayReasonInboundBacklog': 'Inbound exceeds outbound',
      'putawayReasonNoFastLane': 'no free A/B fast-lane slots detected',
      'putawayReasonBlockedSlots': '{n} blocked slots in sample',
      'putawayReasonOk': 'Optional: putaway flow currently looks stable.',
      'putawayReasonRecommended': 'Recommended: {parts}.',
      'putawayExecuteLabel': 'Plan putaway',
      'putawayExecuteDoneLabel': 'Putaway refreshed',
      'putawayExecuteSummary':
          '{total} target slots marked ({fast} fast lane, {reserve} reserve, {blocked} blocked).',
      'putawayExecuteSummaryEmpty':
          'No putaway target slots detected.',
    },
  };
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .any((supported) => supported.languageCode == locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}

extension AppLocalizationExtension on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);

  String tr(String key, [Map<String, Object> params = const {}]) {
    return l10n.tr(key, params);
  }
}
